name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Run linters
        run: pnpm lint

      - name: Run unit test
        run: pnpm test

      - name: Build the extension
        run: pnpm build

      - name: Publish the extension
        run: pnpm run publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
